//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/util/concurrent/FutureFallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonUtilConcurrentFutureFallback")
#ifdef RESTRICT_ComGoogleCommonUtilConcurrentFutureFallback
#define INCLUDE_ALL_ComGoogleCommonUtilConcurrentFutureFallback 0
#else
#define INCLUDE_ALL_ComGoogleCommonUtilConcurrentFutureFallback 1
#endif
#undef RESTRICT_ComGoogleCommonUtilConcurrentFutureFallback

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonUtilConcurrentFutureFallback_) && (INCLUDE_ALL_ComGoogleCommonUtilConcurrentFutureFallback || defined(INCLUDE_ComGoogleCommonUtilConcurrentFutureFallback))
#define ComGoogleCommonUtilConcurrentFutureFallback_

@protocol ComGoogleCommonUtilConcurrentListenableFuture;

@protocol ComGoogleCommonUtilConcurrentFutureFallback < JavaObject >

- (id<ComGoogleCommonUtilConcurrentListenableFuture>)createWithNSException:(NSException *)t;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonUtilConcurrentFutureFallback)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentFutureFallback)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonUtilConcurrentFutureFallback")
