//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:gson-2.6.2-sources.jar!com/google/gson/internal/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonInternalPackage_info")
#ifdef RESTRICT_ComGoogleGsonInternalPackage_info
#define INCLUDE_ALL_ComGoogleGsonInternalPackage_info 0
#else
#define INCLUDE_ALL_ComGoogleGsonInternalPackage_info 1
#endif
#undef RESTRICT_ComGoogleGsonInternalPackage_info

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonInternalPackage_info")
