//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:gson-2.6.2-sources.jar!com/google/gson/reflect/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleGsonReflectPackage_info")
#ifdef RESTRICT_ComGoogleGsonReflectPackage_info
#define INCLUDE_ALL_ComGoogleGsonReflectPackage_info 0
#else
#define INCLUDE_ALL_ComGoogleGsonReflectPackage_info 1
#endif
#undef RESTRICT_ComGoogleGsonReflectPackage_info

#pragma pop_macro("INCLUDE_ALL_ComGoogleGsonReflectPackage_info")
