//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/InterruptibleStream.java
//

#include "InterruptibleStream.h"
#include "J2ObjC_source.h"

@interface UkAcCamClRendezvousInterruptibleStream : NSObject

@end

#line 1 "/Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/InterruptibleStream.java"


#line 14
@implementation UkAcCamClRendezvousInterruptibleStream

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(isOpen);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _UkAcCamClRendezvousInterruptibleStream = { "InterruptibleStream", "uk.ac.cam.cl.rendezvous", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_UkAcCamClRendezvousInterruptibleStream;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(UkAcCamClRendezvousInterruptibleStream)
