//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/RendezvousInputStream.java
//

/*!
 @brief Copyright Pico project, 2016
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RendezvousInputStream")
#ifdef RESTRICT_RendezvousInputStream
#define INCLUDE_ALL_RendezvousInputStream 0
#else
#define INCLUDE_ALL_RendezvousInputStream 1
#endif
#undef RESTRICT_RendezvousInputStream

#if !defined (UkAcCamClRendezvousRendezvousInputStream_) && (INCLUDE_ALL_RendezvousInputStream || defined(INCLUDE_UkAcCamClRendezvousRendezvousInputStream))
#define UkAcCamClRendezvousRendezvousInputStream_

#define RESTRICT_JavaIoInputStream 1
#define INCLUDE_JavaIoInputStream 1
#include "java/io/InputStream.h"

#define RESTRICT_InterruptibleStream 1
#define INCLUDE_UkAcCamClRendezvousInterruptibleStream 1
#include "InterruptibleStream.h"

@class IOSByteArray;
@class UkAcCamClRendezvousRendezvousChannel;

/*!
 @brief An InputStream for accessing data written to a Rendezvous point.
 @author Max Spencer <ms955@@cl.cam.ac.uk>
 */
@interface UkAcCamClRendezvousRendezvousInputStream : JavaIoInputStream < UkAcCamClRendezvousInterruptibleStream >

#pragma mark Public

/*!
 @brief Construct a <code>RendezvousInputStream</code> with the rendezvous point's URL.
 @param rendezvousChannel url of the rendezvous point.
 */
- (instancetype)initWithUkAcCamClRendezvousRendezvousChannel:(UkAcCamClRendezvousRendezvousChannel *)rendezvousChannel;

- (jint)available;

/*!
 @brief Closes the input stream, any reads will be closed when they time out.
 */
- (void)close;

- (jboolean)isOpen;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)b;

- (jint)readWithByteArray:(IOSByteArray *)b
                  withInt:(jint)off
                  withInt:(jint)len;

@end

J2OBJC_EMPTY_STATIC_INIT(UkAcCamClRendezvousRendezvousInputStream)

FOUNDATION_EXPORT void UkAcCamClRendezvousRendezvousInputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousInputStream *self, UkAcCamClRendezvousRendezvousChannel *rendezvousChannel);

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousInputStream *new_UkAcCamClRendezvousRendezvousInputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousChannel *rendezvousChannel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousInputStream *create_UkAcCamClRendezvousRendezvousInputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousChannel *rendezvousChannel);

J2OBJC_TYPE_LITERAL_HEADER(UkAcCamClRendezvousRendezvousInputStream)

#endif

#pragma pop_macro("INCLUDE_ALL_RendezvousInputStream")
