//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/RendezvousOutputStream.java
//

/*!
 @brief Copyright Pico project, 2016
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RendezvousOutputStream")
#ifdef RESTRICT_RendezvousOutputStream
#define INCLUDE_ALL_RendezvousOutputStream 0
#else
#define INCLUDE_ALL_RendezvousOutputStream 1
#endif
#undef RESTRICT_RendezvousOutputStream

#if !defined (UkAcCamClRendezvousRendezvousOutputStream_) && (INCLUDE_ALL_RendezvousOutputStream || defined(INCLUDE_UkAcCamClRendezvousRendezvousOutputStream))
#define UkAcCamClRendezvousRendezvousOutputStream_

#define RESTRICT_JavaIoOutputStream 1
#define INCLUDE_JavaIoOutputStream 1
#include "java/io/OutputStream.h"

#define RESTRICT_InterruptibleStream 1
#define INCLUDE_UkAcCamClRendezvousInterruptibleStream 1
#include "InterruptibleStream.h"

@class IOSByteArray;
@class UkAcCamClRendezvousRendezvousChannel;

@interface UkAcCamClRendezvousRendezvousOutputStream : JavaIoOutputStream < UkAcCamClRendezvousInterruptibleStream >

#pragma mark Public

- (instancetype)initWithUkAcCamClRendezvousRendezvousChannel:(UkAcCamClRendezvousRendezvousChannel *)rendezvousChannel;

/*!
 @brief Closes the output stream, any writes that have not been acknowledged will be cancelled when
 they time out.
 */
- (void)close;

- (jboolean)isOpen;

- (void)writeWithByteArray:(IOSByteArray *)b
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)writeWithInt:(jint)b;

@end

J2OBJC_EMPTY_STATIC_INIT(UkAcCamClRendezvousRendezvousOutputStream)

FOUNDATION_EXPORT void UkAcCamClRendezvousRendezvousOutputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousOutputStream *self, UkAcCamClRendezvousRendezvousChannel *rendezvousChannel);

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousOutputStream *new_UkAcCamClRendezvousRendezvousOutputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousChannel *rendezvousChannel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousOutputStream *create_UkAcCamClRendezvousRendezvousOutputStream_initWithUkAcCamClRendezvousRendezvousChannel_(UkAcCamClRendezvousRendezvousChannel *rendezvousChannel);

J2OBJC_TYPE_LITERAL_HEADER(UkAcCamClRendezvousRendezvousOutputStream)

#endif

#pragma pop_macro("INCLUDE_ALL_RendezvousOutputStream")
