//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/RendezvousChannel.java
//

/*!
 @brief Copyright Pico project, 2016
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RendezvousChannel")
#ifdef RESTRICT_RendezvousChannel
#define INCLUDE_ALL_RendezvousChannel 0
#else
#define INCLUDE_ALL_RendezvousChannel 1
#endif
#undef RESTRICT_RendezvousChannel

#if !defined (UkAcCamClRendezvousRendezvousChannel_) && (INCLUDE_ALL_RendezvousChannel || defined(INCLUDE_UkAcCamClRendezvousRendezvousChannel))
#define UkAcCamClRendezvousRendezvousChannel_

@class IOSByteArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaNetHttpURLConnection;
@class JavaNetURL;

@interface UkAcCamClRendezvousRendezvousChannel : NSObject

#pragma mark Public

- (instancetype)initWithJavaNetURL:(JavaNetURL *)url;

- (instancetype)initWithJavaNetURL:(JavaNetURL *)url
                           withInt:(jint)timeout;

- (void)close;

- (JavaIoInputStream *)getInputStream;

- (JavaIoOutputStream *)getOutputStream;

- (JavaNetURL *)getUrl;

- (void)setTimeoutWithInt:(jint)ms;

#pragma mark Package-Private

- (JavaNetHttpURLConnection *)attemptRead;

- (JavaNetHttpURLConnection *)attemptWriteWithByteArray:(IOSByteArray *)bytes;

@end

J2OBJC_EMPTY_STATIC_INIT(UkAcCamClRendezvousRendezvousChannel)

FOUNDATION_EXPORT void UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_(UkAcCamClRendezvousRendezvousChannel *self, JavaNetURL *url);

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousChannel *new_UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_(JavaNetURL *url) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousChannel *create_UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_(JavaNetURL *url);

FOUNDATION_EXPORT void UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_withInt_(UkAcCamClRendezvousRendezvousChannel *self, JavaNetURL *url, jint timeout);

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousChannel *new_UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_withInt_(JavaNetURL *url, jint timeout) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkAcCamClRendezvousRendezvousChannel *create_UkAcCamClRendezvousRendezvousChannel_initWithJavaNetURL_withInt_(JavaNetURL *url, jint timeout);

J2OBJC_TYPE_LITERAL_HEADER(UkAcCamClRendezvousRendezvousChannel)

#endif

#pragma pop_macro("INCLUDE_ALL_RendezvousChannel")
