//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/StatusResponse.java
//

/*!
 @brief Copyright Pico project, 2016
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StatusResponse")
#ifdef RESTRICT_StatusResponse
#define INCLUDE_ALL_StatusResponse 0
#else
#define INCLUDE_ALL_StatusResponse 1
#endif
#undef RESTRICT_StatusResponse

#if !defined (UkAcCamClRendezvousStatusResponse_) && (INCLUDE_ALL_StatusResponse || defined(INCLUDE_UkAcCamClRendezvousStatusResponse))
#define UkAcCamClRendezvousStatusResponse_

@class JavaNetHttpURLConnection;

@interface UkAcCamClRendezvousStatusResponse : NSObject {
 @public
  jint code_;
  NSString *status_;
  NSString *message_;
}

#pragma mark Public

+ (UkAcCamClRendezvousStatusResponse *)fromConnectionWithJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)connection;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(UkAcCamClRendezvousStatusResponse)

J2OBJC_FIELD_SETTER(UkAcCamClRendezvousStatusResponse, status_, NSString *)
J2OBJC_FIELD_SETTER(UkAcCamClRendezvousStatusResponse, message_, NSString *)

inline jint UkAcCamClRendezvousStatusResponse_get_CLOSED();
#define UkAcCamClRendezvousStatusResponse_CLOSED -1
J2OBJC_STATIC_FIELD_CONSTANT(UkAcCamClRendezvousStatusResponse, CLOSED, jint)

inline jint UkAcCamClRendezvousStatusResponse_get_OK();
#define UkAcCamClRendezvousStatusResponse_OK 0
J2OBJC_STATIC_FIELD_CONSTANT(UkAcCamClRendezvousStatusResponse, OK, jint)

inline jint UkAcCamClRendezvousStatusResponse_get_TIMED_OUT();
#define UkAcCamClRendezvousStatusResponse_TIMED_OUT 2
J2OBJC_STATIC_FIELD_CONSTANT(UkAcCamClRendezvousStatusResponse, TIMED_OUT, jint)

FOUNDATION_EXPORT UkAcCamClRendezvousStatusResponse *UkAcCamClRendezvousStatusResponse_fromConnectionWithJavaNetHttpURLConnection_(JavaNetHttpURLConnection *connection);

J2OBJC_TYPE_LITERAL_HEADER(UkAcCamClRendezvousStatusResponse)

#endif

#pragma pop_macro("INCLUDE_ALL_StatusResponse")
