//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/StatusResponse.java
//

#include "Gson.h"
#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "IOUtils.h"
#include "J2ObjC_source.h"
#include "StatusResponse.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/net/HttpURLConnection.h"

@interface UkAcCamClRendezvousStatusResponse ()

- (instancetype)init;

@end

__attribute__((unused)) static void UkAcCamClRendezvousStatusResponse_init(UkAcCamClRendezvousStatusResponse *self);

__attribute__((unused)) static UkAcCamClRendezvousStatusResponse *new_UkAcCamClRendezvousStatusResponse_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static UkAcCamClRendezvousStatusResponse *create_UkAcCamClRendezvousStatusResponse_init();

#line 1 "/Users/adamroberts/Documents/Workspace6/JRendezvous/src/uk/ac/cam/cl/rendezvous/StatusResponse.java"


#line 15
@implementation UkAcCamClRendezvousStatusResponse


#line 21
+ (UkAcCamClRendezvousStatusResponse *)fromConnectionWithJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)connection {
  return UkAcCamClRendezvousStatusResponse_fromConnectionWithJavaNetHttpURLConnection_(connection);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 45
- (instancetype)init {
  UkAcCamClRendezvousStatusResponse_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 54
- (NSString *)description {
  return [new_ComGoogleGsonGson_init() toJsonWithId:self];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LUkAcCamClRendezvousStatusResponse;", 0x9, 0, 1, 2, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 3, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(fromConnectionWithJavaNetHttpURLConnection:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "CLOSED", "I", .constantValue.asInt = UkAcCamClRendezvousStatusResponse_CLOSED, 0x19, -1, -1, -1, -1 },
    { "OK", "I", .constantValue.asInt = UkAcCamClRendezvousStatusResponse_OK, 0x19, -1, -1, -1, -1 },
    { "TIMED_OUT", "I", .constantValue.asInt = UkAcCamClRendezvousStatusResponse_TIMED_OUT, 0x19, -1, -1, -1, -1 },
    { "code_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "status_", "LNSString;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "message_", "LNSString;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "fromConnection", "LJavaNetHttpURLConnection;", "LJavaIoIOException;", "toString" };
  static const J2ObjcClassInfo _UkAcCamClRendezvousStatusResponse = { "StatusResponse", "uk.ac.cam.cl.rendezvous", ptrTable, methods, fields, 7, 0x10, 3, 6, -1, -1, -1, -1, -1 };
  return &_UkAcCamClRendezvousStatusResponse;
}

@end


#line 21
UkAcCamClRendezvousStatusResponse *UkAcCamClRendezvousStatusResponse_fromConnectionWithJavaNetHttpURLConnection_(JavaNetHttpURLConnection *connection) {
  UkAcCamClRendezvousStatusResponse_initialize();
  
#line 24
  if ([((JavaNetHttpURLConnection *) nil_chk(connection)) getResponseCode] != 200) {
    @throw new_JavaIoIOException_initWithNSString_(@"response code was not 200 OK");
  }
  
#line 28
  if ([connection getContentLength] <= 0) {
    @throw new_JavaIoIOException_initWithNSString_(@"response was empty response");
  }
  
#line 32
  if (![((NSString *) nil_chk([connection getContentType])) isEqual:@"application/json"]) {
    @throw new_JavaIoIOException_initWithNSString_(@"status response was not JSON-encoded");
  }
  
#line 38
  IOSByteArray *responseBytes = [IOSByteArray newArrayWithLength:[connection getContentLength]];
  OrgApacheCommonsIoIOUtils_readFullyWithJavaIoInputStream_withByteArray_([connection getInputStream], responseBytes);
  
#line 41
  NSString *responseString = [NSString stringWithBytes:responseBytes charsetName:@"UTF-8"];
  return [new_ComGoogleGsonGson_init() fromJsonWithNSString:responseString withIOSClass:UkAcCamClRendezvousStatusResponse_class_()];
}


#line 45
void UkAcCamClRendezvousStatusResponse_init(UkAcCamClRendezvousStatusResponse *self) {
  NSObject_init(self);
}


#line 45
UkAcCamClRendezvousStatusResponse *new_UkAcCamClRendezvousStatusResponse_init() {
  J2OBJC_NEW_IMPL(UkAcCamClRendezvousStatusResponse, init)
}


#line 45
UkAcCamClRendezvousStatusResponse *create_UkAcCamClRendezvousStatusResponse_init() {
  J2OBJC_CREATE_IMPL(UkAcCamClRendezvousStatusResponse, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(UkAcCamClRendezvousStatusResponse)
