/**
 * @file
 * @author  David Llewellyn-Jones <David.Llewellyn-Jones@cl.cam.ac.uk>
 * @version 1.0
 *
 * @section LICENSE
 *
 * Copyright Pico project, 2016
 *
 * @section DESCRIPTION
 *
 * The MessageServiceReAuth class allows a Status message to ge generated by
 * the server to be sent to the Pico.
 * 
 * This represents a message sent as part of the continuous authentication
 * process.
 * QR-code (KeyAuth or KeyPair); Start; ServiceAuth; PicoAuth; Status;
 * Pico ReAuth; Service ReAuth (repeatedly).
 *
 * The structure of the message is as follows
 * {"iv":"B64","encryptedData":"B64-ENC","sessionId":0}
 * Where encryptedData contains the following sections
 * char reauthState | int timeout | length | char sequenceNumber[length]
 *
 */

#ifndef __MESSAGESERVICEREAUTH_H
#define __MESSAGESERVICEREAUTH_H (1)

#include "pico/shared.h"
#include "pico/buffer.h"
#include "pico/sequencenumber.h"
#include "pico/messagepicoreauth.h"

// Defines

// 10 seconds
#define CONTINUOUS_TIMEOUT_ACTIVE (10000)
#define CONTINUOUS_TIMEOUT_PAUSED (50000)
#define CONTINUOUS_TIMEOUT_LEEWAY (10000)

// Structure definitions

typedef struct _MessageServiceReAuth MessageServiceReAuth;

// Function prototypes

MessageServiceReAuth * messageservicereauth_new();
void messageservicereauth_delete(MessageServiceReAuth * messageservicereauth);
void messageservicereauth_set(MessageServiceReAuth * messageservicereauth, Buffer * sharedKey, long int timeout, REAUTHSTATE reauthState, SequenceNumber const * sequenceNum);
void messageservicereauth_serialize(MessageServiceReAuth * messageservicereauth, Buffer * buffer);

// Function definitions

#endif

