/**
 * @file
 * @author  David Llewellyn-Jones <David.Llewellyn-Jones@cl.cam.ac.uk>
 * @version 1.0
 *
 * @section LICENSE
 *
 * Copyright Pico project, 2016
 *
 * @section DESCRIPTION
 *
 * The MessageServiceAuth class allows a ServiceAuth message to ge generated by
 * the server to be sent to the Pico.
 * 
 * This represents the second message forming the first round trip of the
 * Sigma-I protocol:
 * QR-code (KeyAuth or KeyPair); Start; ServiceAuth; PicoAuth; Status.
 *
 * The structure of the message is as follows
 * {"serviceEphemPublicKey":"B64-PUB-KEY","serviceNonce":"B64-NONCE","sessionId":0,"encryptedData":"B64-ENC","iv":"B64"}
 *
 */

#ifndef __MESSAGESERVICEAUTH_H
#define __MESSAGESERVICEAUTH_H (1)

#include <openssl/ec.h>
#include "pico/keypair.h"
#include "pico/nonce.h"
#include "pico/shared.h"
#include "pico/buffer.h"

// Defines

// Structure definitions

typedef struct _MessageServiceAuth MessageServiceAuth;

// Function prototypes

MessageServiceAuth * messageserviceauth_new();
void messageserviceauth_delete(MessageServiceAuth * messageserviceauth);
void messageserviceauth_set(MessageServiceAuth * messageserviceauth, Shared * shared, int sessionId);
void messageserviceauth_serialize(MessageServiceAuth * messageserviceauth, Buffer * buffer);

// Function definitions

#endif

