/**
 * @file
 * @author  David Llewellyn-Jones <David.Llewellyn-Jones@cl.cam.ac.uk>
 * @version 1.0
 *
 * @section LICENSE
 *
 * Copyright Pico project, 2016
 *
 * @section DESCRIPTION
 *
 * The MessageStatus class allows a Status message to ge generated by
 * the server to be sent to the Pico.
 * 
 * This represents the second message forming the second round trip of the
 * Sigma-I protocol:
 * QR-code (KeyAuth or KeyPair); Start; ServiceAuth; PicoAuth; Status.
 *
 * The structure of the message is as follows
 * {"iv":"B64","encryptedData":"B64-ENC","sessionId":0}
 *
 */

#ifndef __MESSAGESTATUS_H
#define __MESSAGESTATUS_H (1)

#include "pico/shared.h"
#include "pico/buffer.h"

// Defines

#define MESSAGESTATUS_OK_DONE ((char)0)
#define MESSAGESTATUS_OK_CONTINUE ((char)1)
#define MESSAGESTATUS_REJECTED ((char)-1)

// Structure definitions

typedef struct _MessageStatus MessageStatus;

// Function prototypes

MessageStatus * messagestatus_new();
void messagestatus_delete(MessageStatus * messagestatus);
void messagestatus_set(MessageStatus * messagestatus, Shared * shared, char const * extraData, char status);
void messagestatus_serialize(MessageStatus * messagestatus, Buffer * buffer);
void messagestatus_set_session_id(MessageStatus * messagestatus, int sessionId);

// Function definitions

#endif

