/**
 * @file
 * @author  David Llewellyn-Jones <David.Llewellyn-Jones@cl.cam.ac.uk>
 * @version 1.0
 *
 * @section LICENSE
 *
 * Copyright Pico project, 2016
 *
 * @section DESCRIPTION
 *
 * The Shared class encapsulates all of the shared data and secrets needed to
 * perform the Sigma-I protocol. For example, identity keys, ephemeral keys,
 * nonces and shared generates secrets.
 *
 * Some of the contents are provided at creation (e.g. the service identity
 * key, whereas others are added as the protocol progresses.
 * 
 */

#include <stdio.h>
#include <openssl/ec.h>
#include <stdlib.h>
#include "pico/debug.h"
#include "pico/buffer.h"
#include "pico/nonce.h"
#include "pico/keypair.h"
#include "pico/sigmakeyderiv.h"
#include "pico/keyagreement.h"
#include "pico/log.h"
#include "pico/shared.h"

// Defines

// Structure definitions

/**
 * Structure containing the private fields of the class.
 */
struct _Shared {
	Buffer * pMacKey;
	Buffer * pEncKey;
	Buffer * vMacKey;
	Buffer * vEncKey;
	Buffer * sharedKey;

	Nonce * serviceNonce;
	Nonce * picoNonce;

	KeyPair * serviceIdentityKey;
	KeyPair * serviceEphemeralKey;
    KeyPair * picoIdentityKey;
    KeyPair * picoEphemeralKey;
	EC_KEY * picoIdentityPublicKey;
	EC_KEY * picoEphemeralPublicKey;
    EC_KEY * serviceIdentityPublicKey;
    EC_KEY * serviceEphemeralPublicKey;
    const char * extraData;
};

// Function prototypes

void shared_generate_shared_secrets(Shared * shared);

// Function definitions

/**
 * Create a new instance of the class.
 *
 * @return The newly created object.
 */
Shared * shared_new() {
	Shared * shared;

	shared = CALLOC(sizeof(Shared), 1);

	shared->pMacKey = buffer_new(32); // 256 bits
	shared->pEncKey = buffer_new(16); // 128 bits
	shared->vMacKey = buffer_new(32); // 256 bits
	shared->vEncKey = buffer_new(16); // 128 bits
	shared->sharedKey = buffer_new(16); // 128 bits

	shared->serviceNonce = nonce_new();
	nonce_generate_random(shared->serviceNonce);

	shared->picoNonce = nonce_new();

	shared->serviceIdentityKey = keypair_new();
	shared->serviceEphemeralKey = keypair_new();
    shared->picoIdentityKey = keypair_new();
    shared->picoEphemeralKey = keypair_new();

	shared->picoIdentityPublicKey = NULL;
	shared->picoEphemeralPublicKey = NULL;
    shared->serviceIdentityPublicKey = NULL;
    shared->serviceEphemeralPublicKey = NULL;

	return shared;
}

/**
 * Delete an instance of the class, freeing up the memory allocated to it.
 *
 * @param shared The object to free.
 */
void shared_delete(Shared * shared) {
	if (shared) {
		if (shared->pMacKey) {
			buffer_delete(shared->pMacKey);
		}
		if (shared->pEncKey) {
			buffer_delete(shared->pEncKey);
		}
		if (shared->vMacKey) {
			buffer_delete(shared->vMacKey);
		}
		if (shared->vEncKey) {
			buffer_delete(shared->vEncKey);
		}
		if (shared->sharedKey) {
			buffer_delete(shared->sharedKey);
		}
		if (shared->serviceNonce) {
			nonce_delete(shared->serviceNonce);
		}
		if (shared->picoNonce) {
			nonce_delete(shared->picoNonce);
		}
		if (shared->serviceIdentityKey) {
			keypair_delete(shared->serviceIdentityKey);
		}
		if (shared->serviceEphemeralKey) {
			keypair_delete(shared->serviceEphemeralKey);
		}
		if (shared->picoIdentityPublicKey) {
			EC_KEY_free(shared->picoIdentityPublicKey);
		}
		if (shared->picoEphemeralPublicKey) {
			EC_KEY_free(shared->picoEphemeralPublicKey);
		}
		FREE(shared);
	}
}

/**
 * Attempts to laod the public and private keys from the files named. If this
 * fails because the failes don't exist, a new set of keys is generated and
 * are saved out to the files, as well as being stored in the Shared object.
 *
 * @param shared The shared object to store the keys in
 * @param key_public Full filename of the public key to attempt to load
 * @param key_private Full filename of the private key to attempt to load
 */
void shared_load_or_generate_keys(Shared * shared, char const * key_public, char const * key_private) {
	KeyPair * serviceIdentityKey;
	bool result;

	serviceIdentityKey = shared_get_service_identity_key(shared);
	result = keypair_import(serviceIdentityKey, key_public, key_private);
	if (!result) {
		keypair_generate(serviceIdentityKey);
		keypair_export(serviceIdentityKey, key_public, key_private);
	}
}

/**
 * Generate a series of shared secrets needed to complete the Pico protocol.
 * The secrets are generated from the ephemeral private key of the service
 * and the ephemeral public key of the Pico. The resulting shared secrets are
 * stored in the Shared object and used for various purposes, including
 * encrypting future messages, signing messages and generating MACs.
 * Note that these secrets can be generated by both the service and the Pico.
 *
 * @param shared The Shared object to get the keys from and store the results 
 *               in
 */
void shared_generate_shared_secrets(Shared * shared) {
	Buffer * sharedSecret;
	EVP_PKEY * vEphemPriv;
	SigmaKeyDeriv * sigmakeyderiv;

	// Generate ECDH shared secret
	sharedSecret = buffer_new(0);

	vEphemPriv = keypair_getprivatekey(shared->serviceEphemeralKey);

	keyagreement_generate_secret(vEphemPriv, shared->picoEphemeralPublicKey, sharedSecret);

	// Generate key data
	sigmakeyderiv = sigmakeyderiv_new();
	sigmakeyderiv_set(sigmakeyderiv, sharedSecret, shared->picoNonce, shared->serviceNonce);
	buffer_delete(sharedSecret);

	sigmakeyderiv_get_next_key(sigmakeyderiv, shared->pMacKey, 256);

	sigmakeyderiv_get_next_key(sigmakeyderiv, shared->pEncKey, 128);

	sigmakeyderiv_get_next_key(sigmakeyderiv, shared->vMacKey, 256);

	sigmakeyderiv_get_next_key(sigmakeyderiv, shared->vEncKey, 128);

	sigmakeyderiv_get_next_key(sigmakeyderiv, shared->sharedKey, 128);

	sigmakeyderiv_delete(sigmakeyderiv);
}

void shared_generate_shared_secrets_pico(Shared * shared) {
    Buffer * sharedSecret;
    EVP_PKEY * pEphemPriv;
    SigmaKeyDeriv * sigmakeyderiv;
    
    // Generate ECDH shared secret
    sharedSecret = buffer_new(0);
    
    pEphemPriv = keypair_getprivatekey(shared->picoEphemeralKey);
    
    keyagreement_generate_secret(pEphemPriv, shared->serviceEphemeralPublicKey, sharedSecret);
    
    // Generate key data
    sigmakeyderiv = sigmakeyderiv_new();
    sigmakeyderiv_set(sigmakeyderiv, sharedSecret, shared->picoNonce, shared->serviceNonce);
    buffer_delete(sharedSecret);
    
    sigmakeyderiv_get_next_key(sigmakeyderiv, shared->pMacKey, 256);
    
    sigmakeyderiv_get_next_key(sigmakeyderiv, shared->pEncKey, 128);
    
    sigmakeyderiv_get_next_key(sigmakeyderiv, shared->vMacKey, 256);
    
    sigmakeyderiv_get_next_key(sigmakeyderiv, shared->vEncKey, 128);
    
    sigmakeyderiv_get_next_key(sigmakeyderiv, shared->sharedKey, 128);
    
    sigmakeyderiv_delete(sigmakeyderiv);
}

/**
 * Returns the service's nonce from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The service's nonce
 */
Nonce * shared_get_service_nonce(Shared * shared) {
	return shared->serviceNonce;
}

void shared_set_extra_data(Shared * shared, const char * ed) {
    shared->extraData = ed;;
}

const char * shared_get_extra_data(Shared * shared) {
    return shared->extraData;
}

/**
 * Returns the Pico's nonce from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The Pico's nonce
 */
Nonce * shared_get_pico_nonce(Shared * shared) {
	return shared->picoNonce;
}

/**
 * Returns the service's long term identity key pair from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The service's long term identity key pair
 */
KeyPair * shared_get_service_identity_key(Shared * shared) {
	return shared->serviceIdentityKey;
}

/**
 * Returns the pico's long term identity key pair from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The service's long term identity key pair
 */
KeyPair * shared_get_pico_identity_key(Shared * shared) {
    return shared->picoIdentityKey;
}

/**
 * Returns the service's ephemeral key pair from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The service's ephemeral key pair
 */
KeyPair * shared_get_service_ephemeral_key(Shared * shared) {
	return shared->serviceEphemeralKey;
}

/**
 * Returns the picos's ephemeral key pair from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The service's ephemeral key pair
 */
KeyPair * shared_get_pico_ephemeral_key(Shared * shared) {
    return shared->picoEphemeralKey;
}

/**
 * Sets the Pico's long term identity public key.
 *
 * @param shared The Shared object to store the details in
 */
void shared_set_pico_identity_public_key(Shared * shared, EC_KEY * picoIdentityPublicKey) {
	shared->picoIdentityPublicKey = picoIdentityPublicKey;
}

/**
 * Sets the Service's long term identity public key.
 *
 * @param shared The Shared object to store the details in
 */
void shared_set_service_identity_public_key(Shared * shared, EC_KEY * serviceIdentityPublicKey) {
    shared->serviceIdentityPublicKey = serviceIdentityPublicKey;
}

/**
 * Gets the Service's long term identity public key.
 *
 * @param shared The Shared object to store the details in
 */
EC_KEY * shared_get_service_identity_public_key(Shared * shared) {
    return shared->serviceIdentityPublicKey;
}

/**
 * Returns the Pico's long term identity public key from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The Pico's long term identity public key
 */
EC_KEY * shared_get_pico_identity_public_key(Shared * shared) {
	return shared->picoIdentityPublicKey;
}

/**
 * Sets the Pico's ephemeral public key.
 *
 * @param shared The Shared object to store the details in
 */
void shared_set_pico_ephemeral_public_key(Shared * shared, EC_KEY * picoEphemeralPublicKey) {
	shared->picoEphemeralPublicKey = picoEphemeralPublicKey;
}

/**
 * Sets the Service's ephemeral public key.
 *
 * @param shared The Shared object to store the details in
 */
void shared_set_service_ephemeral_public_key(Shared * shared, EC_KEY * serviceEphemeralPublicKey) {
    shared->serviceEphemeralPublicKey = serviceEphemeralPublicKey;
}

/**
 * Returns the Pico's ephemeral public key from the Shared object.
 *
 * @param shared The Shared object to get the details from
 * @return The Pico's ephemeral public key
 */
EC_KEY * shared_get_pico_ephemeral_public_key(Shared * shared) {
	return shared->picoEphemeralPublicKey;
}

EC_KEY * shared_get_service_ephemeral_public_key(Shared * shared) {
    return shared->serviceEphemeralPublicKey;
}

/**
 * Returns a buffer to the Pico's symmetric encryption key.
 *
 * @param shared The Shared object to get the details from
 * @return A buffer containing the Pico's symmetric encryption key. This buffer
 *         is part of the Shared object, so should not be deleted (it will be
 *         automatically deleted when the Shared object is)
 */
Buffer * shared_get_prover_enc_key(Shared * shared) {
	return shared->pEncKey;
}

/**
 * Returns a buffer to the Service's symmetric encryption key.
 *
 * @param shared The Shared object to get the details from
 * @return A buffer containing the Service's symmetric encryption key. This 
 *         buffer is part of the Shared object, so should not be deleted (it 
 *         will be automatically deleted when the Shared object is)
 */
Buffer * shared_get_verifier_enc_key(Shared * shared) {
	return shared->vEncKey;
}

/**
 * Returns a buffer to the Pico's symmetric MAC key.
 *
 * @param shared The Shared object to get the details from
 * @return A buffer containing the Pico's symmetric MAC key. This buffer
 *         is part of the Shared object, so should not be deleted (it will be
 *         automatically deleted when the Shared object is)
 */
Buffer * shared_get_prover_mac_key(Shared * shared) {
	return shared->pMacKey;
}

/**
 * Returns a buffer to the Service's symmetric MAC key.
 *
 * @param shared The Shared object to get the details from
 * @return A buffer containing the Service's symmetric MAC key. This 
 *         buffer is part of the Shared object, so should not be deleted (it 
 *         will be automatically deleted when the Shared object is)
 */
Buffer * shared_get_verifier_mac_key(Shared * shared) {
	return shared->vMacKey;
}

/**
 * Returns a buffer to the shared key.
 *
 * @param shared The Shared object to get the details from
 * @return A buffer containing the shared symmetric key. This 
 *         buffer is part of the Shared object, so should not be deleted (it 
 *         will be automatically deleted when the Shared object is)
 */
Buffer * shared_get_shared_key(Shared * shared) {
	return shared->sharedKey;
}


